name: custom-conditions
description: Inject Steps with custom conditions.
author: https://github.com/tobig77
requirements:
  - docker
configuration:
  properties:
    name:
      type: string
    type:
      type: string
    git-path:
      type: string
    cache-prefix:
      type: string
    tags:
      type: [ string, array ]
  additionalProperties: false