name: custom-conditions
description: Inject Steps with custom conditions.
author: https://github.com/tobig77
requirements:
  - docker
configuration:
  properties:
    condition: string
    git-path: string
    script-path: string
    ssm-prefix: string
  additionalProperties: false