name: custom-conditions
description: Inject Steps with custom conditions.
author: https://github.com/tobig77
requirements:
  - docker
configuration:
  properties:
    name: string
    type: string
    git-path: string
    cache-prefix: string
  additionalProperties: false