#!/usr/bin/env bash
set -euo pipefail

[ "${BUILDKITE_PLUGIN_DEBUG:-false}" == "true" ] && set -x ||:

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

PLUGIN_STAGE="post-command"

# shellcheck source=lib/shared.sh
. "$DIR/../lib/shared.sh"

